### ISSUE TITLE
SpecsFor MVC .NET 4.6 Compatibility

### ISSUE THREAD

**Issue by Workshop2** [MattHoneycutt/SpecsFor#70] opened 2015-05-22 22:25 UTC
If you try and run a test for MVC targeting a .NET 4.6 app you will get lots of build errors due to the wrong MSBUILD being run.

I have got a temp fix, however something in the framework should be updated: https://gist.github.com/Workshop2/c9114fcd959bf4e1dfcf

**Comment by MattHoneycutt** [comment] 2015-08-14 02:14
It's taken me a bit to get back to this, but I'm finally trying to triage open issues.  I was unable to reproduce a build error with .NET 4.6 and the current version of SpecsFor.Mvc.  Can you provide me with some more details about your setup?  

1) Which version of ASP.NET MVC is being referenced by your web project?
2) Which version of ASP.NET MVC is being referenced by your spec project?
3) Which framework version is each project using? 

Thanks!

**Comment by Workshop2** [comment] 2015-10-12 22:19
It was 4.6, but the machine has never had VS 2013/2010 installed. Not sure if that helps?

**Comment by MattHoneycutt** [comment] 2017-02-21 23:15
Closing for now.  I'm open to investigating further if someone can supply me with a working reproduction repo for this.

**Closed by MattHoneycutt** 2017-02-21 23:15 UTC
